stages:
 - build
 - test
 - deploy

gradle-build:
  image: gradle:4.7-jdk8
  stage: build
  script:
    - gradle clean build
  artifacts:
    when: always
    paths:
      - build/libs/*.jar
      - build/reports/tests/test

pages:
  when: always
  stage: deploy
  dependencies:
    - gradle-build
  script:
    - mkdir public
    - mv build/reports/tests/test/* public/
  artifacts:
    when: always
    paths:
      - public

heroku-deploy:
  image: docker
  stage: deploy
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/tourister-java.git
    - git push -f heroku master
